### ISSUE TITLE
More Datasources

### ISSUE THREAD

**Issue by breaches-net** [notdls/known-breaches#1]
Hey, just came across this project and I love it. Here are some more data-sources I have if you're interested. Some of these are gathered from Wayback Archive, since quite a few of these services don't exist anymore. WeLeakInfo has 2 different ones because they use to show breach lists in a different format. None of these would need to be re-scraped since most of them (Like WeLeakInfo, Hacked-Emails & Citadel to name a few don't exist anymore). I use most of these sources when adding breaches to the list on https://breaches.net, and so far they've been mostly accurate.

Files (All CSV Formatted):
[LeakFind [leakfindrg5s2zcwwdmxlvz6oefz6hdwlkckh4eir4huqcpjsefxkead.onion] breaches.csv](https://github.com/notdls/known-breaches/files/8648512/LeakFind.leakfindrg5s2zcwwdmxlvz6oefz6hdwlkckh4eir4huqcpjsefxkead.onion.breaches.csv)
[WeLeakInfo #1 [weleakinfo.com] breaches.csv](https://github.com/notdls/known-breaches/files/8648516/WeLeakInfo.1.weleakinfo.com.breaches.csv)
[WeLeakInfo #2 [weleakinfo.com] breaches.csv](https://github.com/notdls/known-breaches/files/8648517/WeLeakInfo.2.weleakinfo.com.breaches.csv)
[Snusbase [snusbase.com] breaches.csv](https://github.com/notdls/known-breaches/files/8648518/Snusbase.snusbase.com.breaches.csv)
[Keeper [keeper.io] breaches.csv](https://github.com/notdls/known-breaches/files/8648520/Keeper.keeper.io.breaches.csv)
[Hacked Emails [hacked-emails.com] breaches.csv](https://github.com/notdls/known-breaches/files/8648521/Hacked.Emails.hacked-emails.com.breaches.csv)
[databases.today [databases.today] breaches.csv](https://github.com/notdls/known-breaches/files/8648524/databases.today.databases.today.breaches.csv)
[DeepSearch [xjypo5vzgmo7jca6b322dnqbsdnp3amd24ybx26x5nxbusccjkm4pwid.onion] breaches.csv](https://github.com/notdls/known-breaches/files/8648527/DeepSearch.xjypo5vzgmo7jca6b322dnqbsdnp3amd24ybx26x5nxbusccjkm4pwid.onion.breaches.csv)
[Citadel [citadel.pw] breaches.csv](https://github.com/notdls/known-breaches/files/8648533/Citadel.citadel.pw.breaches.csv)
[HackNotice [hacknotice.com] breaches.csv](https://github.com/notdls/known-breaches/files/8648542/HackNotice.hacknotice.com.breaches.csv)

Hope this helps! :)

**Comment by notdls** [comment]
Thanks for the datasources, I've added these and a few more with [2242c33f287cb1266e9fc7b331d4c7b28c17c6a9](https://github.com/notdls/known-breaches/commit/2242c33f287cb1266e9fc7b331d4c7b28c17c6a9)
